version: '3.8'
services:
  dev-db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: my_db
    networks:
      - dev-network
networks:
  dev-network:
